CREATE DATABASE db_RedeSocial

CREATE TABLE Usuarios(
ID INT PRIMARY KEY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
Senha VARCHAR(50) NOT NULL
)

CREATE TABLE Tema(
ID INT PRIMARY KEY NOT NULL,
Descricao VARCHAR(100) NOT NULL
)

CREATE TABLE Postagens(
ID INT PRIMARY KEY NOT NULL,
Titulo VARCHAR(100) NULL,
Descricao VARCHAR(100) NULL,
FK_Usuario INT NOT NULL,
FK_Temas INT NOT NULL
FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (ID),
FOREIGN KEY (FK_Temas) REFERENCES Tema (ID)
)

