CREATE DATABASE db_Ecomerce

CREATE TABLE Usuarios(
ID INT PRIMARY KEY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
Senha VARCHAR(50) NOT NULL,
CPF INT NOT NULL
)

CREATE TABLE Compras(
ID INT PRIMARY KEY NOT NULL,
Valor FLOAT NULL,
Total FLOAT NULL,
FormaDePagamento VARCHAR(MAX) NOT NULL,
FK_Usuario INT NOT NULL,
FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (ID)
)

CREATE TABLE PRODUTOS(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Preco FLOAT NULL,
Quantidade INT NULL,
Categoria VARCHAR(MAX) NOT NULL,
FK_Compra INT NOT NULL,
FOREIGN KEY (FK_Compra) REFERENCES Compras (ID) 
)
